#!/bin/sh
basedir=$(realpath "$(dirname "$0")")
pnpm i -C "$basedir/frontend" build
find "$basedir"/backend/public -mindepth 1 -delete
mkdir -p "$basedir"/frontend/out/
pnpm run -C "$basedir/frontend" build
cp -rv "$basedir"/frontend/out/* "$basedir"/backend/public
go build -C "$basedir/backend"
