#!/usr/bin/sh
basedir=$(realpath $(dirname "$0"))
cp -v "$basedir/installfiles/gnuplex.service" /etc/systemd/system/gnuplex.service
systemctl enable gnuplex
mkdir -v /etc/gnuplex
sh "$basedir/build"
cp -v "$basedir/backend/gnuplex-backend" /usr/bin
