name: Update Release Branch on Version Change

on:
  push:
    branches:
      - main
    paths:
      - 'backend/consts/version.go'

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required for git log and merge
    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: setup bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.23.2'
        cache-dependency-path: backend/go.sum
    - name: Update Release Branch
      run: |
        git checkout release || git checkout -b release
        git merge main -X theirs --allow-unrelated-histories
        bundle install
        bundle exec rake build
        version_output=$(./backend/bin/gnuplex -version)
        git config user.name "deploy.yml workflow"
        git config user.email "x@example.com"
        git add .
        git commit -m "Release: $version_output"
        git push origin release