name: Update release-linux-musl-x86_64 on version change

on:
  push:
    branches:
      - main
    paths:
      - "backend/consts/version.go"

jobs:
  update-release-linux-musl-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: setup docker
        uses: docker/setup-docker-action@v4
      - name: create alpine build
        run: |
          docker run -v $(realpath .github/workflows):/mnt/build:z alpine:3 sh /mnt/build/build_and_publish_alpine.sh "${{ secrets.GNUPLEX_DEPLOY }}"
