name: Update Release Branch for linux-x86_64 on Version Change

on:
  push:
    branches:
      - main
    paths:
      - "backend/consts/version.go"

jobs:
  update-release-linux-glibc-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23.2"
          cache-dependency-path: backend/go.sum
      - name: setup docker
        uses: docker/setup-docker-action@v4
      - name: merge main into release
        run: |
          git remote set-url origin git@github.com:janie314/gnuplex.git
          git config user.name "release workflow"
          git config user.email "x@example.com"
          git checkout release-linux-musl-x86_64
          git merge main -X theirs --allow-unrelated-histories
      - name: create alpine build
        run: |
          docker run -v $(realpath .github/workflows):/mnt/build:z alpine:edge sh /mnt/build/build_and_publish_alpine.sh "${{ secrets.GNUPLEX_DEPLOY }}"