on:
  pull_request:
  push:
    branches:
      - main
      - release
jobs:
  test:
    runs-on: ubuntu-latest
    name: testing and linting this branch
    steps:
    - name: check out this repo
      uses: actions/checkout@v4
    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
    - name: setup ruby
      uses: oven-sh/setup-bun@v2
    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.23.2'
        cache-dependency-path: backend/go.sum
    - name: compile the go backend
      working-directory: backend
      run: |
        go build .
    - name: check go formatting
      working-directory: backend
      run: |
        gofmt -s -d . | wc -l | xargs ruby -e 'exit (ARGV[0].to_i > 0 ? 1 : 0)'
    - name: lint frontend code
      run: |
        bun i
        bun run biome ci