on:
  pull_request:
  push:
    branches:
      - main
      - release
jobs:
  test:
    runs-on: ubuntu-latest
    name: testing and linting this branch
    steps:
    - name: check out this repo
      uses: actions/checkout@v4
      with:
        lfs: true
    - run: git lfs pull -I gnuplex
    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: setup bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.23.2'
        cache-dependency-path: backend/go.sum
    - name: compile the go backend
      working-directory: backend
      run: |
        bundle exec rake go_build
    - name: check go formatting
      working-directory: backend
      run: |
        gofmt -s -d . | wc -l | xargs ruby -e 'exit (ARGV[0].to_i > 0 ? 1 : 0)'
    - name: lint frontend code
      run: |
        pwd
        bun run -i biome ci
    - name: lint ruby code
      run: |
        bundle exec rubocop
    - name: check frontend build was run
      working-directory: frontend
      run: |
        bundle exec rake frontend_build
        git status --porcelain | wc -l | xargs ruby -e 'exit (ARGV[0].to_i > 0 ? 1 : 0)'
    - name: check backend build was run
      run: |
        bundle exec rake go_build_current
    - name: check for TODOs
      run: |
        grep -rnI . \
          --exclude-dir .github --exclude-dir .git --exclude-dir node_modules --exclude-dir .git \
          -e TODO | wc -l | xargs ruby -e 'exit (ARGV[0].to_i > 0 ? 1 : 0)'
