on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    name: go checks
    steps:
    - name: check out this repo
      uses: actions/checkout@v4
    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.23.2'
    - name: compile the go backend
      run: go build -C backend .